/*
 * source: file bases on https://github.com/linaro-swg/optee_examples/blob/master/hello_world/ta/include/hello_world_ta.h
 */

#ifndef COFFEE_TRACKING_CHAINCODE_H
#define COFFEE_TRACKING_CHAINCODE_H


/*
 * uuid for coffee tracking chaincode (generated by http://www.itu.int/ITU-T/asn1/uuid.html)
 */
#define TA_COFFEE_CHAINCODE_UUID \
	{ 0x6ceb95ba, 0xe9b1, 0x482a, \ 
		{ 0xa1, 0xbd, 0xa1, 0xeb, 0xca, 0x06, 0x71, 0xb9 }}

/* used to store the state of the invocated transaction (add, create or query) */
#define ADD_GET_STATE 0
#define ADD_PUT_STATE 1
#define ADD_WRITE_RESPONSE 2
#define CREATE_GET_STATE 0
#define CREATE_PUT_STATE 1
#define CREATE_WRITE_RESPONSE 2
#define QUERY_GET_STATE 0
#define QUERY_WRITE_RESPONSE 1
		
#endif /*COFFEE_TRACKING_CHAINCODE_CHAINCODE_H*/
